version: "3.8"

services:
  app:
    build: .
    container_name: bot
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Ссылаемся на переменную из .env
    volumes:
      - .:/opt/app
    command: ["python", "main.py"]

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Ссылаемся на переменную из .env
