[tool.poetry]
name = "newtimetable"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.5.0"
python-dotenv = "^1.0.1"
sentry-sdk = "^1.45.0"
httpx = "^0.27.0"
pymongo = "^4.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
