[project]
name = "newtimetable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0",
    "httpx>=0.28.1",
    "pymongo>=4.12.0",
    "python-dotenv>=1.1.0",
    "redis>=5.2.1",
]
